image: python:3.11

stages:
  - deploy

pages:
  stage: deploy
  script:
    - pip install --upgrade pip
    - pip install mkdocs mkdocs-material mkdocstrings[python]
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main  # Or 'master', depending on your default branch