image: python:3.11

stages:
  - deploy

pages:
  stage: deploy
  script:
    - pip install --upgrade pip
    - pip install mkdocs mkdocs-material mkdocstrings[python]
    - mkdocs build  # this already outputs to public/
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main  # or 'master'