image: python:3.11

stages:
  - deploy

pages:
  stage: deploy
  script:
    - pip install --upgrade pip
    - pip install mkdocs mkdocs-material mkdocstrings[python]
    - echo "Building site..."
    - mkdocs build --verbose
    - echo "Contents of public directory:"
    - ls -la public/
    - echo "Checking if index.html exists:"
    - ls -la public/index.html || echo "index.html not found!"
    - echo "First few lines of index.html:"
    - head -20 public/index.html 2>/dev/null || echo "Cannot read index.html"
    - echo "Total size of public directory:"
    - du -sh public/
  artifacts:
    paths:
      - public
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == "main"  # Modern GitLab syntax instead of 'only'