image: python:3.11

before_script:
  - pip install mkdocs mkdocs-material mkdocstrings[python]

pages:
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - main  # or 'master', depending on your default branch
