image: python:3.10
1

pages:
  stage: deploy
  script:
    - pip install --upgrade pip
    - pip install mkdocs mkdocs-material mkdocstrings[python]
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - main  # or your default branch name
