image: python:3.11

pages:
  before_script:
    - pip install mkdocs mkdocs-material
  script:
    - mkdocs build
    - mv site public  # GitLab Pages expects a `public/` folder
  artifacts:
    paths:
      - public
  only:
    - main  # or your default branch
