site_name: SQEALI
site_url: https://chucknorriscake.github.io/sqeali
use_directory_urls: true 
docs_dir: docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

nav:
  - Home: index.md
  - Simulation Base: simbase.md
  - Ring Resonator: ringresonator.md
  - Linear Waveguide: linearwaveguide.md