site_name: SQEALI
site_url: https://chucknorriscake.github.io/SQEALI
use_directory_urls: true  # Change to true for better GitHub Pages compatibility
docs_dir: docs

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

nav:
  - Home: index.md
  - Simulation Base: simbase.md
  - Ring Resonator: ringresonator.md
  - Linear Waveguide: linearwaveguide.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences