site_name: SQEALI
site_url: https://julianverhey.physics.unitn.it/advancedphotonicsmeep
use_directory_urls: false

theme:
  name: material

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

nav:
  - Home: index.md
  - Simulation Base: simbase.md
  - Ring Resonator: ringresonator.md
  - Linear Waveguide: linearwaveguide.md
